### ISSUE TITLE
Doesn't show as active plugin

### ISSUE THREAD

**Issue by atilladapun** [Magnum97/BreedablePetsMC#3]
Placed the file, in original downloaded form, into plugins folder but it does not show in server after '/reload'
Is there a .jar that should be in the folder or in plugin folder?
![Breedablepets issue](https://user-images.githubusercontent.com/63978089/79698867-aa9aa200-8240-11ea-9763-11ad753f5568.png)
Thank you for making this, I have been trying to get a working parrot breeder for a while!

**Comment by Magnum97** [comment]
Thank you. I'm glad it is appreciated. If you run `./gradlew jar` or `gradlew.bat jar` on Windows, it will build the jar and place it in build/libs directory.

**Comment by Magnum97** [comment]
@atilladapun 
After trying to build on a different PC I found that I used a local library that I forgot to include in the repository. I am rewriting to integrate that library into the code as well as make some updates for Minecraft 1.15. I will update this issue when I get those done. Glad you brought this to my attention. ^_^

**Comment by Magnum97** [comment]
[x] Change materials for 1.13+ compatability
 [x] Integrate code from local library
 [] Fix reading config for chance of hatch

**Comment by Magnum97** [comment]
Woo Good news @atilladapun ! I have it working. Life has been crazy recently and there are still things I want to do or change but a working dev version can be downloaded from [this page](https://github.com/Magnum97/BreedablePetsMC/actions/runs/110147551).
Thank you for your interest and I welcome any feedback you may have.

**Comment by atilladapun** [comment]
Thank you so much! Life has indeed been crazy, but I appreciate you working at this!
Perhaps you could help me figure out how to make the gradlew.bat function, or where it should be outputting. Do I need a specific program to help this build the .jar?
It did what seemed like a full run of it the first time and then afterward attempting to run it causes 
 it to say it failed and close the window. Maybe because there's already a file in the output spot? I couldn't find the .jar within the  "breedablepetsMC-master" folder though. Thank you for your help!
